import 'package:malitours/models/site_model.dart';

List<SiteModel> sites = [
  SiteModel(
      id: '1',
      nom: 'Musé Nationale',
      adresse: 'Quatier du fleuve',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '2',
      nom: 'Parc Nationale',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '3',
      nom: 'Le campement',
      adresse: 'Niamana',
      tarif: 1500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Domaine Kanu',
      adresse: 'Koulicoro',
      tarif: 5000,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
  SiteModel(
      id: '1',
      nom: 'Badaloge',
      adresse: 'Roule de Koulouba',
      tarif: 500,
      image: 'assets/images/bamako.jpeg',
      ville: 'Bamako'),
];
